Uiregistration
MTU-CS3141-Team15/CS3141-R02-team15 pull request #12
Opened 2022-04-08 23:49 UTC by Chanpech

Just got done finalizing the last few things on the registration page. The <link href=> for "Don't have an account? Sign Up" should take you to the registration page and vice versa for "Already have an account". We can remove the register from the hamburger menu if you deem it necessary. There shouldn't be any more of the prettier/prettier compile error.

2022-04-09 14:04 UTC, tjzetty approved these changes
Good implementation of the register page. Should be super easy to hook up.

2022-04-10 01:48 UTC, tjquillan requested changes

2022-04-10 01:48 UTC, tjquillan commented on .prettierignore
> +␍/
Lets not ignore / for formatting. Might ignore everything? Not quite sure...

2022-04-10 01:48 UTC, tjquillan commented on apps/frontend/src/components/App.tsx
> +            <ListItemNavLink to="/register" primary="Register" />
Register should only be sent to by buttons / direct links. Not the navbar

2022-04-10 01:48 UTC, tjquillan commented on apps/frontend/src/components/App.tsx
> +          <Route path="/register" element={<Register />} />
Duplicate routs?

2022-04-10 01:48 UTC, tjquillan commented on apps/frontend/src/pages/Login.tsx
> +              <Link href="/register" variant="body2">
This doesn't seem to use react-roughter

2022-04-10 01:48 UTC, tjquillan commented on apps/frontend/src/pages/Register.tsx
> +              <Link href="/login" variant="body2">
Should also use react-router

2022-04-10 02:19 UTC, tjquillan approved these changes

2022-04-10 02:21 UTC, merged