Delete habit + Delete unit test
MTU-CS3141-Team15/CS3141-R02-team15 pull request #13
Opened 2022-04-09 00:27 UTC by Chanpech

The delete habit branch is ready to merge. This branch composes of the delete endpoint and the delete unit test.

2022-04-09 13:54 UTC, tjzetty reviewed
Should probably clean up habit.ts. I am not super familiar with the backend API endpoints but probably shouldn't PR huge comment blocks. Looks really good though from what I can tell.

2022-04-10 01:43 UTC, tjquillan requested changes

2022-04-10 01:43 UTC, tjquillan commented on apps/backend/package.json
> +        "supertest": "^6.2.2"
Supertest is not needed as a dependency

2022-04-10 01:43 UTC, tjquillan commented on apps/backend/src/routes/habit.ts
> +import { userInfo } from "os";
This seem like it might have been imported by accident?

2022-04-10 01:43 UTC, tjquillan commented on apps/backend/src/routes/habit.ts
> +*/
Comment can probably be removed

2022-04-10 01:43 UTC, tjquillan commented on apps/backend/test/habit.test.ts
> +import { prisma } from "@prisma/client";
Also seems to be an accidental import?

2022-04-10 02:02 UTC, tjquillan approved these changes

2022-04-10 02:12 UTC, merged